POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "pero otra más todavía",
  "important": false
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{

}

